package sol.desk.wjjst;

import java.util.Random;

public class AllChampionName {
	public String ChapName(int champNo) {
		
		switch (champNo) {
		case 1:
			return "애니";
		case 2:
			return "올라프";
		case 3:
			return "갈리오";
		case 4:
			return "트위스트페이트";
		case 5:
			return "신짜오";
		case 6:
			return "우르곳";
		case 7:
			return "르블랑";
		case 8:
			return "블라디미르";
		case 9:
			return "피들스틱";
		case 10:
			return "케일";
		case 11:
			return "마스터이";
		case 12:
			return "알리스타";
		case 13:
			return "라이즈";
		case 14:
			return "사이온";
		case 15:
			return "시비르";
		case 16:
			return "소라카";
		case 17:
			return "티모";
		case 18:
			return "트리스타나";
		case 19:
			return "워윅";
		case 20:
			return "누누";
		case 21:
			return "미스포츈";
		case 22:
			return "애쉬";
		case 23:
			return "트린다미어";
		case 24:
			return "잭스";
		case 25:
			return "모르가나";
		case 26:
			return "질리언";
		case 27:
			return "신지드";
		case 28:
			return "이블린";
		case 29:
			return "트위치";
		case 30:
			return "카서스";
		case 31:
			return "초가스";
		case 32:
			return "아무무";
		case 33:
			return "람머스";
		case 34:
			return "애니비아";
		case 35:
			return "샤코";
		case 36:
			return "문도박사";
		case 37:
			return "소나";
		case 38:
			return "카사딘";
		case 39:
			return "이렐리야";
		case 40:
			return "잔나";
		case 41:
			return "갱플랭크";
		case 42:
			return "코르키";
		case 43:
			return "카르마";
		case 44:
			return "타릭";
		case 45:
			return "베이가";
		case 48:
			return "트런들";
		case 50:
			return "스웨인";
		case 51:
			return "케이틀린";
		case 53:
			return "블리츠크랭크";
		case 54:
			return "구른다돌멩이";
		case 55:
			return "카타리나";
		case 56:
			return "녹턴";
		case 57:
			return "마오게이";
		case 58:
			return "레넥통";
		case 59:
			return "자르반";
		case 60:
			return "엘리스";
		case 61:
			return "오리아나";
		case 62:
			return "오공";
		case 63:
			return "브랜드";
		case 64:
			return "리띤";
		case 67:
			return "베인";
		case 68:
			return "럼블";
		case 69:
			return "카시오페아";
		case 72:
			return "스카너";
		case 74:
			return "하이머딩거";
		case 75:
			return "나서스";
		case 76:
			return "니달리";
		case 77:
			return "우디르";
		case 78:
			return "뽀삐";
		case 79:
			return "그라가스";
		case 80:
			return "빵테온";
		case 81:
			return "이즈리얼";
		case 82:
			return "모데카이저";
		case 83:
			return "요릭";
		case 84:
			return "아칼리";
		case 85:
			return "케넨";
		case 86:
			return "킹렌";
		case 89:
			return "레오나";
		case 90:
			return "말자하";
		case 91:
			return "탈수기탈론";
		case 92:
			return "리븐";
		case 96:
			return "침뱉는고구마";
		case 98:
			return "쉔";
		case 99:
			return "럭스쨩";
		case 101:
			return "제라스";
		case 102:
			return "용가리쉬바나";
		case 103:
			return "아리쨔응";
		case 104:
			return "그레이브즈";
		case 105:
			return "피즈";
		case 106:
			return "콜라곰";
		case 107:
			return "렝가";
		case 110:
			return "바루스";
		case 111:
			return "노딜러스";
		case 112:
			return "빅토르:번개의신";
		case 113:
			return "세주아니";
		case 114:
			return "피오라";
		case 115:
			return "직스";
		case 117:
			return "요롤로룰루";
		case 119:
			return "홍철이";
		case 120:
			return "헥카림";
		case 121:
			return "깨직스";
		case 122:
			return "다리우스";
		case 126:
			return "제이스";
		case 127:
			return "리산드라반반";
		case 131:
			return "다이애나";
		case 133:
			return "퀸";
		case 134:
			return "신드라";
		case 136:
			return "아우렐리온솔";
		case 143:
			return "자이라";
		case 150:
			return "나르";
		case 154:
			return "자크";
		case 157:
			return "야스오(과학)";
		case 161:
			return "벨코즈";
		case 163:
			return "탈리야탈탈";
		case 164:
			return "카밀";
		case 201:
			return "브라움";
		case 202:
			return "진";
		case 203:
			return "킨드레드";
		case 222:
			return "징크스";
		case 223:
			return "두꺼비";
		case 236:
			return "루시안";
		case 238:
			return "제드";
		case 240:
			return "클레드";
		case 245:
			return "에코";
		case 254:
			return "바이";
		case 266:
			return "아트록스";
		case 267:
			return "나미";
		case 268:
			return "비둘기";
		case 412:
			return "쓰레기";
		case 420:
			return "일라오이";
		case 421:
			return "렉사이";
		case 427:
			return "숲의요정";
		case 429:
			return "칼리스타";
		case 432:
			return "바드";
		
			
		default :
			return "신챔은 등록이 안되있습니다.";
		}
		
	}
	
}
